export default [
  {variants: ['Jr', 'II', 'Junior', 'Jnr'], canonical: 'jr', type: 'generational'},
  {variants: ['Sr', 'I', 'Senior', 'Snr'], canonical: 'sr', type: 'generational'},
  {variants: ['III'], canonical: 'iii', type: 'generational'},
  {variants: ['IV'], canonical: 'iv', type: 'generational'},
  {variants: ['V'], canonical: 'v', type: 'generational'},
  {variants: ['VI'], canonical: 'vi', type: 'generational'},
  {variants: ['VII'], canonical: 'vii', type: 'generational'},

  {variants: ['C.S.V.'], canonical: 'csv', type: 'religious'},
  {variants: ['O.F.M.'], canonical: 'ofm', type: 'religious'},

  {variants: ['ASCAP'], canonical: 'ascap', type: 'professional'},
  {variants: ['CEng'], canonical: 'ceng', type: 'professional'},
  {variants: ['CFA'], canonical: 'cfa', type: 'professional'},
  {variants: ['CISA', 'CISSP', 'CISM'], canonical: 'cism', type: 'professional'},
  {variants: ['CPA'], canonical: 'cpa', type: 'professional'},
  {variants: ['CPL'], canonical: 'cpl', type: 'professional'},
  {variants: ['CSA'], canonical: 'csa', type: 'professional'},
  {variants: ['Esq', 'Esquire'], canonical: 'esq', type: 'professional'},
  {variants: ['MCSP', 'SRP'], canonical: 'srp', type: 'professional'},
  {variants: ['MEOA'], canonical: 'meoa', type: 'professional'},
  {variants: ['PE'], canonical: 'pe', type: 'professional'},
  {variants: ['PG'], canonical: 'pg', type: 'professional'},
  {variants: ['PMP'], canonical: 'pmp', type: 'professional'},
  {variants: ['PT'], canonical: 'pt', type: 'professional'},
  {variants: ['R.A.', 'AIA', 'RIBA'], canonical: 'ra', type: 'professional'},
  {variants: ['RN'], canonical: 'rn', type: 'professional'},

  {variants: ['B.A.', 'A.B.'], canonical: 'ba', type: 'academic'},
  {variants: ['B.S.', 'B.Sc.'], canonical: 'bs', type: 'academic'},
  {variants: ['D.C.'], canonical: 'dc', type: 'academic'},
  {variants: ['D.O.'], canonical: 'do', type: 'academic'},
  {variants: ['J.D.'], canonical: 'jd', type: 'academic'},
  {variants: ['M.A.'], canonical: 'ma', type: 'academic'},
  {variants: ['M.B.A.'], canonical: 'ma', type: 'academic'},
  {variants: ['M.S.', 'M.Sc.'], canonical: 'bs', type: 'academic'},
  {variants: ['M.D.'], canonical: 'md', type: 'academic'},
  {variants: ['Ph.D.'], canonical: 'phd', type: 'academic'}
];
